/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Rock Large by Quaternius
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Rock_Large_2: THREE.Mesh;
  };
  materials: {
    Atlas: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function EnvironmentLargeRock(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/RockLarge.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock_Large_2.geometry} material={materials.Atlas} scale={100} />
    </group>
  );
}

useGLTF.preload('/models/RockLarge.glb');
