/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/models/Plant.glb -t 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Plant_3: THREE.Mesh;
  };
  materials: {
    Atlas: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function EnvironmentPlant(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Plant.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plant_3.geometry} material={materials.Atlas} scale={100} />
    </group>
  );
}

useGLTF.preload('/models/Plant.glb');
